"""Record what a generated file was derived from, inside the file itself.

Several artefacts in the analysis are expensive to produce and are committed to
the repository once made: the effective event counts cost thousands of batch
jobs. Regenerating them because nobody could tell whether they were still valid
is waste, and overwriting a hand-maintained one is worse.

So each generated file carries a header naming its direct inputs by content
hash. A later run can then answer "are these still the inputs I would use?"
without recomputing anything, and refuse to touch a file it did not write.

Content hashes rather than commit ids: a commit changes whenever anything in the
repository changes, including files this artefact never read, so it would
invalidate far more often than the artefact actually goes stale. The commit is
recorded alongside for traceability, but never used to decide staleness.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from workflow_automation.cli import BootstrapError


MARKER = "# workflow-automation-provenance:"
SCHEMA_VERSION = 1


def digest(path: Path) -> str:
    if not path.is_file():
        raise BootstrapError(f"cannot fingerprint a missing input: {path}")
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def describe(inputs: dict[str, Path], extra: dict[str, object] | None = None) -> dict[str, object]:
    """Fingerprint the direct inputs of an artefact."""
    return {
        "schema_version": SCHEMA_VERSION,
        "inputs": {name: digest(path) for name, path in sorted(inputs.items())},
        **(extra or {}),
    }


def read(path: Path) -> dict[str, object] | None:
    """Return the provenance recorded in a file, or None if it carries none.

    None means the file was not written by this workflow. That is deliberately
    distinguishable from a stale record, because the two deserve different
    treatment: one is out of date, the other is somebody else's work.
    """
    if not path.is_file():
        return None
    try:
        with path.open("r", errors="replace") as stream:
            for _ in range(20):
                line = stream.readline()
                if not line:
                    break
                if line.startswith(MARKER):
                    return json.loads(line[len(MARKER):].strip())
    except (OSError, json.JSONDecodeError):
        return None
    return None


def matches(path: Path, expected: dict[str, object]) -> bool:
    """Whether a file was generated from exactly these inputs."""
    recorded = read(path)
    if not recorded:
        return False
    return recorded.get("inputs") == expected.get("inputs")


def stamp(path: Path, payload: dict[str, object]) -> None:
    """Prepend the provenance header to a file that has just been generated.

    Written as a comment so that every consumer of these YAML files keeps
    parsing them unchanged, while the record stays visible in the file and in
    review of any commit that changes it.
    """
    body = path.read_text()
    if body.startswith(MARKER):
        body = "\n".join(body.splitlines()[1:]) + "\n"
    recorded = dict(payload)
    recorded.setdefault("generated_at", datetime.now(timezone.utc).isoformat())
    header = f"{MARKER} {json.dumps(recorded, sort_keys=True, separators=(',', ':'))}\n"
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(header + body)
    temporary.replace(path)


def guard_overwrite(path: Path, allow_overwrite: bool) -> None:
    """Refuse to overwrite an artefact this workflow did not generate.

    A file with no provenance header was written by somebody, by hand or by an
    older process, and its contents are the only record of that work.
    """
    if not path.is_file() or allow_overwrite:
        return
    if read(path) is None:
        raise BootstrapError(
            f"{path} exists but carries no provenance header, so it was not generated by "
            "this workflow and overwriting it would discard whatever produced it. Rerun "
            "with --allow-overwrite if replacing it is intended."
        )
